POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "camariana",
  "name": "A Camariana",
  "password": "jannata"
}
