POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbWFyaWFuYSIsImlkIjoiNjBiYThjODQ0OWIzMjU0YWUzZDFiZDBmIiwiaWF0IjoxNjIyODg3MDc1LCJleHAiOjE2MjI4OTA2NzV9.U4qCGYEUiKF6BKYCV0h2psnLnNdYLm7SH66TZnEvzUw

  {
    "title": "An Open Letter to Jason and David",
    "author": "Jane Yang",
    "url": "https://janeyang.org/2021/04/27/an-open-letter-to-jason-and-david/",
    "likes": 9
  }
  # {
  #   "title": "Which jobs help people the most?",
  #   "author": "Benjamin Todd",
  #   "url": "https://80000hours.org/career-guide/high-impact-jobs/#approach-1-earning-to-give",
  #   "likes": 2
  # }
  # {
  #   "title": "React patterns",
  #   "author": "Michael Chan",
  #   "url": "https://reactpatterns.com/",
  # }
  # {
  #   "title": "Go To Statement Considered Harmful",
  #   "author": "Edsger W. Dijkstra",
  #   "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  #   "likes": 5,
  # },
  # {
  #   "title": "Canonical string reduction",
  #   "author": "Edsger W. Dijkstra",
  #   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  #   "likes": 12,
  # },
  # {
  #   "title": "First class tests",
  #   "author": "Robert C. Martin",
  #   "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
  #   "likes": 10,
  # },


###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "b",
  "name": "Binta Dibba",
  "password": "di"
}


###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

# {
#   "username": "mluukkai",
#   "password": "salainen"
# }
{
  "username": "camariana",
  "password": "jannata"
}
# {
#   "username": "falisco",
#   "password": "efaal"
# }
# {
#   "username": "lamin",
#   "password": "lbarrow"
# }
